// Account Detail Types
export const ADD_ACCOUNT_DETAILS_REQUEST = "ADD_ACCOUNT_DETAILS_REQUEST";
export const ADD_ACCOUNT_DETAILS_SUCCESS = "ADD_ACCOUNT_DETAILS_SUCCESS";
export const ADD_ACCOUNT_DETAILS_ERROR = "ADD_ACCOUNT_DETAILS_ERROR";