// Ads types
export const ADD_ADS_REQUEST = "ADD_ADS_REQUEST";
export const ADD_ADS_SUCCESS = "ADD_ADS_SUCCESS";
export const ADD_ADS_ERROR = "ADD_ADS_ERROR";

export const SET_ADS_REQUEST = "SET_ADS_REQUEST";
export const SET_ADS_SUCCESS = "SET_ADS_SUCCESS";
export const SET_ADS_ERROR = "SET_ADS_ERROR";

export const UPDATE_ADS_REQUEST = "UPDATE_ADS_REQUEST";
export const UPDATE_ADS_SUCCESS = "UPDATE_ADS_SUCCESS";
export const UPDATE_ADS_ERROR = "UPDATE_ADS_ERROR";

export const SET_SPECIFIC_ADD_TEMPLATE = "SET_SPECIFIC_ADD_TEMPLATE";
