// Campaigns types
export const ADD_CAMPAIGN_REQUEST = "ADD_CAMPAIGN_REQUEST";
export const ADD_CAMPAIGN_SUCCESS = "ADD_CAMPAIGN_SUCCESS";
export const ADD_CAMPAIGN_ERROR = "ADD_CAMPAIGN_ERROR";

export const SET_CAMPAIGN_REQUEST = "SET_CAMPAIGN_REQUEST";
export const SET_CAMPAIGN_SUCCESS = "SET_CAMPAIGN_SUCCESS";
export const SET_CAMPAIGN_ERROR = "SET_CAMPAIGN_ERROR";

export const UPDATE_CAMPAIGN_REQUEST = "UPDATE_CAMPAIGN_REQUEST";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_ERROR = "UPDATE_CAMPAIGN_ERROR";
