// Company Detail Types
export const ADD_COMPANY_DETAILS_REQUEST = "ADD_COMPANY_DETAILS_REQUEST";
export const ADD_COMPANY_DETAILS_SUCCESS = "ADD_COMPANY_DETAILS_SUCCESS";
export const ADD_COMPANY_DETAILS_ERROR = "ADD_COMPANY_DETAILS_ERROR";
