// Profile Account Types
export const ADD_PROFILE_ACCOUNT_REQUEST = "ADD_PROFILE_ACCOUNT_REQUEST";
export const ADD_PROFILE_ACCOUNT_SUCCESS = "ADD_PROFILE_ACCOUNT_SUCCESS";
export const ADD_PROFILE_ACCOUNT_ERROR = "ADD_PROFILE_ACCOUNT_ERROR";

export const UPDATE_PROFILE_ACCOUNT_REQUEST = "UPDATE_PROFILE_ACCOUNT_REQUEST";
export const UPDATE_PROFILE_ACCOUNT_SUCCESS = "UPDATE_PROFILE_ACCOUNT_SUCCESS";
export const UPDATE_PROFILE_ACCOUNT_ERROR = "UPDATE_PROFILE_ACCOUNT_ERROR";

export const SET_PROFILE_ACCOUNT_REQUEST = "SET_PROFILE_ACCOUNT_REQUEST";
export const SET_PROFILE_ACCOUNT_SUCCESS = "SET_PROFILE_ACCOUNT_SUCCESS";
export const SET_PROFILE_ACCOUNT_ERROR = "SET_PROFILE_ACCOUNT_ERROR";

export const SET_PROFILE_ACCOUNT_IMAGE_REQUEST = "SET_PROFILE_ACCOUNT_IMAGE_REQUEST";
export const SET_PROFILE_ACCOUNT_IMAGE_SUCCESS = "SET_PROFILE_ACCOUNT_IMAGE_SUCCESS";
export const SET_PROFILE_ACCOUNT_IMAGE_ERROR = "SET_PROFILE_ACCOUNT_IMAGE_ERROR";

export const SET_PROFILE_ACCOUNT_STATE = "SET_PROFILE_ACCOUNT_STATE";
