// Target Audience Types
export const ADD_TARGET_AUDIENCE_REQUEST = "ADD_TARGET_AUDIENCE_REQUEST";
export const ADD_TARGET_AUDIENCE_SUCCESS = "ADD_TARGET_AUDIENCE_SUCCESS";
export const ADD_TARGET_AUDIENCE_ERROR = "ADD_TARGET_AUDIENCE_ERROR";

export const SET_TARGET_AUDIENCE_REQUEST = "SET_TARGET_AUDIENCE_REQUEST";
export const SET_TARGET_AUDIENCE_SUCCESS = "SET_TARGET_AUDIENCE_SUCCESS";
export const SET_TARGET_AUDIENCE_ERROR = "SET_TARGET_AUDIENCE_ERROR";

export const SET_SAMPLE_TARGET_AUDIENCE_REQUEST = "SET_SAMPLE_TARGET_AUDIENCE_REQUEST";
export const SET_SAMPLE_TARGET_AUDIENCE_SUCCESS = "SET_SAMPLE_TARGET_AUDIENCE_SUCCESS";
export const SET_SAMPLE_TARGET_AUDIENCE_ERROR = "SET_SAMPLE_TARGET_AUDIENCE_ERROR";

export const DELETE_TARGET_AUDIENCE = "DELETE_TARGET_AUDIENCE";

export const UPDATE_TARGET_AUDIENCE_REQUEST = "UPDATE_TARGET_AUDIENCE_REQUEST";
export const UPDATE_TARGET_AUDIENCE_SUCCESS = "UPDATE_TARGET_AUDIENCE_SUCCESS";
export const UPDATE_TARGET_AUDIENCE_ERROR = "UPDATE_TARGET_AUDIENCE_ERROR";

export const UPDATE_TARGET_AUDIENCE_PROFILE_REQUEST = "UPDATE_TARGET_AUDIENCE_PROFILE_REQUEST";
export const UPDATE_TARGET_AUDIENCE_PROFILE_SUCCESS = "UPDATE_TARGET_AUDIENCE_PROFILE_SUCCESS";
export const UPDATE_TARGET_AUDIENCE_PROFILE_ERROR = "UPDATE_TARGET_AUDIENCE_PROFILE_ERROR";

export const SET_AUDIENCE_PROFILE = "SET_AUDIENCE_PROFILE";
export const SET_AUDIENCE_PROFILE_NULL = "SET_AUDIENCE_PROFILE_NULL";
export const SET_TARGET_AUDIENCE_STATE = "SET_TARGET_AUDIENCE_STATE";
