// Email template
export const SET_TEMPLATE_EMAIL_REQUEST = "SET_TEMPLATE_EMAIL_REQUEST";
export const SET_TEMPLATE_EMAIL_SUCCESS = "SET_TEMPLATE_EMAIL_SUCCESS";
export const SET_TEMPLATE_EMAIL_ERROR = "SET_TEMPLATE_EMAIL_ERROR";

export const SET_TEMPLATE_REQUEST = "SET_TEMPLATE_REQUEST";
export const SET_TEMPLATE_SUCCESS = "SET_TEMPLATE_SUCCESS";
export const SET_TEMPLATE_ERROR = "SET_TEMPLATE_ERROR";

export const ADD_TEMPLATE_EMAIL_REQUEST = "ADD_TEMPLATE_EMAIL_REQUEST";
export const ADD_TEMPLATE_EMAIL_ERROR = "ADD_TEMPLATE_EMAIL_ERROR";
export const ADD_TEMPLATE_EMAIL_SUCCESS = "ADD_TEMPLATE_EMAIL_SUCCESS";

export const UPDATE_TEMPLATE_EMAIL_REQUEST = "UPDATE_TEMPLATE_EMAIL_REQUEST";
export const UPDATE_TEMPLATE_EMAIL_ERROR = "UPDATE_TEMPLATE_EMAIL_ERROR";
export const UPDATE_TEMPLATE_EMAIL_SUCCESS = "UPDATE_TEMPLATE_EMAIL_SUCCESS";

export const SET_SAMPLE_TEMPLATE_REQUEST = "SET_SAMPLE_TEMPLATE_REQUEST";
export const SET_SAMPLE_TEMPLATE_ERROR = "SET_SAMPLE_TEMPLATE_ERROR";
export const SET_SAMPLE_TEMPLATE_SUCCESS = "SET_SAMPLE_TEMPLATE_SUCCESS";

export const DELETE_TEMPLATE_EMAIL = "DELETE_TEMPLATE_EMAIL";
export const UPDATE_TEMPLATE_EMAIL = "UPDATE_TEMPLATE_EMAIL";
export const SET_TEMPLATE_EMAIL_STATE = "SET_TEMPLATE_EMAIL_STATE";
